import type { LifecycleSnapshot, LifecycleStage } from "@/types/lifecycle";

type StagePageSeed = readonly [string, string, string, string, "not-started" | "pending" | "in-progress" | "completed" | "warning" | "blocked" | "failed", string];

export const analysePages = [
  ["analysis-command", "Analysis Command Dashboard", "Executive view of analysis process and outputs", "/market-intelligence", "in-progress", "chart"],
  ["market-structure", "Market Structure Analysis", "Analyse market structure, trend and price action", "/market-intelligence/institutional-intelligence/market-structure", "completed", "structure"],
  ["multi-timeframe", "Multi-Timeframe Analysis", "MN / W / D / H8 / H4 / H1 alignment", "/market-intelligence/top-down-analysis", "completed", "calendar"],
  ["technical", "Technical Analysis", "Indicators, patterns and technical signals", "/market-intelligence/retail-technical-intelligence", "in-progress", "arrow"],
  ["fundamental", "Fundamental Analysis", "Economic data, news and macro analysis", "/market-intelligence/usd-news-intelligence", "completed", "news"],
  ["sentiment", "Sentiment Analysis", "Market sentiment and positioning intelligence", "/market-intelligence/hybrid-market-interpretation", "in-progress", "sentiment"],
  ["liquidity", "Liquidity & Order-Flow Analysis", "Liquidity zones and institutional order-flow", "/market-intelligence/institutional-intelligence/liquidity-intelligence", "pending", "liquidity"],
  ["support-resistance", "Support & Resistance Intelligence", "Dynamic S/R and key price levels", "/market-intelligence/retail-technical-intelligence/support-and-resistance", "in-progress", "levels"],
  ["gold-bias", "Gold Bias Assessment", "Determine directional bias for XAUUSD", "/market-intelligence/hybrid-market-interpretation/directional-confidence", "in-progress", "bias"],
  ["confluence", "Analysis Confluence Matrix", "Multi-factor confluence scoring", "/market-intelligence/hybrid-market-interpretation/supporting-evidence", "pending", "matrix"],
  ["exceptions", "Analysis Exceptions", "Manage alerts, contradictions and exceptions", "/executive/alerts-and-exceptions", "warning", "warning"],
  ["history", "Analysis History", "Historical analysis results and performance", "/market-intelligence/hybrid-market-interpretation/analysis-history", "completed", "history"],
] as const;

const stagePages: Record<string, readonly StagePageSeed[]> = {
  start: [
    ["start-command", "Start Command Centre", "Activate and supervise the autonomous startup sequence", "/platform-readiness/start", "completed", "rocket"],
    ["operating-mode", "Operating Mode", "Select demo, live, prop-firm or simulation operating state", "/platform-readiness/start/operating-mode", "completed", "settings"],
    ["trading-profile", "Trading Profile", "Load symbol, session and strategy operating preferences", "/platform-readiness/start/trading-profile", "completed", "profile"],
    ["risk-profile", "Risk Profile", "Apply risk model, limits and account protection policy", "/platform-readiness/start/risk-profile", "completed", "shield"],
    ["pre-start-checklist", "Pre-Start Checklist", "Confirm required dependencies before lifecycle launch", "/platform-readiness/start/pre-start-checklist", "completed", "checklist"],
    ["startup-history", "Startup History", "Review previous startup events and audit records", "/platform-readiness/start/startup-history", "completed", "history"],
  ],
  initialize: [
    ["initialization-centre", "Initialization Centre", "Coordinate runtime, model and engine initialization", "/platform-readiness/initialize", "completed", "rocket"],
    ["engine-initialization", "Engine Initialization", "Start workflow, analysis, risk and execution engines", "/platform-readiness/initialize/engine-initialization", "completed", "settings"],
    ["ai-agent-initialization", "AI Agent Initialization", "Load autonomous agents and responsibility routing", "/platform-readiness/initialize/ai-agent-initialization", "completed", "sentiment"],
    ["service-initialization", "Service Initialization", "Prepare transport, storage and real-time services", "/platform-readiness/initialize/service-initialization", "completed", "structure"],
    ["dependency-monitor", "Dependency Monitor", "Check dependencies and runtime readiness signals", "/platform-readiness/initialize/dependency-monitor", "completed", "checklist"],
    ["configuration-loading", "Configuration Loading", "Load trading, session, risk and strategy configuration", "/platform-readiness/initialize/configuration-loading", "completed", "settings"],
    ["initialization-logs", "Initialization Logs", "Inspect initialization logs and exception records", "/platform-readiness/initialize/initialization-logs", "completed", "history"],
  ],
  connect: [
    ["connectivity-centre", "Connectivity Centre", "Monitor all external and internal service connections", "/platform-readiness/connect", "completed", "structure"],
    ["mt5-bridge", "MT5 Bridge", "Connect and monitor MetaTrader bridge status", "/platform-readiness/connect/mt5-bridge", "completed", "liquidity"],
    ["broker-connection", "Broker Connection", "Verify broker account connectivity and trade permissions", "/platform-readiness/connect/broker-connection", "completed", "shield"],
    ["market-data-connection", "Market Data Connection", "Subscribe to XAUUSD tick and candle feeds", "/platform-readiness/connect/market-data-connection", "completed", "chart"],
    ["news-calendar-connection", "News and Calendar Connection", "Connect USD news and economic calendar feeds", "/platform-readiness/connect/news-and-calendar-connection", "completed", "news"],
    ["database-connection", "Database Connection", "Verify production persistence and audit storage", "/platform-readiness/connect/database-connection", "completed", "matrix"],
    ["real-time-messaging", "Real-Time Messaging", "Connect WebSocket and event channels", "/platform-readiness/connect/real-time-messaging", "completed", "arrow"],
    ["connection-history", "Connection History", "Review connection events, drops and recoveries", "/platform-readiness/connect/connection-history", "completed", "history"],
  ],
  validate: [
    ["validation-centre", "Validation Centre", "Coordinate account, symbol, broker and strategy validation", "/platform-readiness/validate", "completed", "checklist"],
    ["account-validation", "Account Validation", "Confirm account eligibility and permissions", "/platform-readiness/validate/account-validation", "completed", "profile"],
    ["gold-symbol-validation", "Gold Symbol Validation", "Validate XAUUSD contract settings and tick value", "/platform-readiness/validate/gold-symbol-validation", "completed", "chart"],
    ["broker-validation", "Broker Validation", "Validate broker execution rules and constraints", "/platform-readiness/validate/broker-validation", "completed", "shield"],
    ["risk-readiness", "Risk Readiness", "Confirm risk limits and emergency protections", "/platform-readiness/validate/risk-readiness", "completed", "shield"],
    ["strategy-readiness", "Strategy Readiness", "Confirm strategy library and activation policy", "/platform-readiness/validate/strategy-readiness", "completed", "matrix"],
    ["trade-reconciliation", "Existing Trade Reconciliation", "Reconcile existing positions and pending orders", "/platform-readiness/validate/existing-trade-reconciliation", "completed", "liquidity"],
    ["validation-exceptions", "Validation Exceptions", "Review validation warnings and blockers", "/platform-readiness/validate/validation-exceptions", "completed", "warning"],
    ["validation-history", "Validation History", "Inspect validation decisions and audit history", "/platform-readiness/validate/validation-history", "completed", "history"],
  ],
  synchronize: [
    ["synchronization-centre", "Synchronization Centre", "Coordinate all market, account and session synchronization", "/platform-readiness/synchronize", "completed", "structure"],
    ["multi-timeframe-sync", "Multi-Timeframe Synchronization", "Synchronize MN, W, D, H12, H8 and intraday context", "/platform-readiness/synchronize/multi-timeframe-synchronization", "completed", "calendar"],
    ["tick-candle-sync", "Tick and Candle Synchronization", "Sync live ticks and historical candle series", "/platform-readiness/synchronize/tick-and-candle-synchronization", "completed", "chart"],
    ["account-state-sync", "Account State Synchronization", "Sync equity, margin, positions and account flags", "/platform-readiness/synchronize/account-state-synchronization", "completed", "profile"],
    ["positions-orders", "Positions and Orders", "Synchronize open positions and pending orders", "/platform-readiness/synchronize/positions-and-orders", "completed", "liquidity"],
    ["news-sync", "News Synchronization", "Sync news, event clocks and restrictions", "/platform-readiness/synchronize/news-synchronization", "completed", "news"],
    ["session-sync", "Session Synchronization", "Sync active trading session and session levels", "/platform-readiness/synchronize/session-synchronization", "completed", "levels"],
    ["time-sync", "Time Synchronization", "Validate time source and timezone alignment", "/platform-readiness/synchronize/time-synchronization", "completed", "calendar"],
    ["data-quality", "Data Quality Monitor", "Monitor gaps, stale ticks and feed integrity", "/platform-readiness/synchronize/data-quality-monitor", "completed", "warning"],
    ["sync-history", "Synchronization History", "Review synchronization logs and recoveries", "/platform-readiness/synchronize/synchronization-history", "completed", "history"],
  ],
  analyse: analysePages,
  plan: [
    ["autonomous-trading-plan", "Autonomous Trading Plan", "Build the active autonomous trading plan", "/strategy-opportunity/plan/autonomous-trading-plan", "pending", "matrix"],
    ["daily-trading-plan", "Daily Trading Plan", "Define daily directional thesis and operating limits", "/strategy-opportunity/plan/daily-trading-plan", "pending", "calendar"],
    ["session-plans", "Session Plans", "Prepare Asian, London and New York playbooks", "/strategy-opportunity/plan/session-plans", "pending", "levels"],
    ["strategy-activation", "Strategy Activation", "Activate compatible strategies for current regime", "/strategy-opportunity/plan/strategy-activation", "pending", "rocket"],
    ["strategy-restrictions", "Strategy Restrictions", "Apply no-trade and risk restrictions", "/strategy-opportunity/plan/strategy-restrictions", "pending", "shield"],
    ["risk-allocation-plan", "Risk Allocation Plan", "Allocate risk across opportunities and sessions", "/strategy-opportunity/plan/risk-allocation-plan", "pending", "shield"],
    ["news-trading-plan", "News Trading Plan", "Plan pre-news and post-news behavior", "/strategy-opportunity/plan/news-trading-plan", "pending", "news"],
    ["trading-windows", "Trading Windows", "Define eligible execution windows", "/strategy-opportunity/plan/trading-windows", "pending", "calendar"],
    ["no-trade-conditions", "No-Trade Conditions", "Review blocked market conditions", "/strategy-opportunity/plan/no-trade-conditions", "pending", "warning"],
    ["daily-objectives", "Daily Objectives", "Track daily objectives and expected action", "/strategy-opportunity/plan/daily-objectives", "pending", "checklist"],
    ["plan-history", "Plan History", "Review previous plans and plan changes", "/strategy-opportunity/plan/plan-history", "pending", "history"],
  ],
  scan: [
    ["scanner-dashboard", "Opportunity Scanner Dashboard", "Monitor live opportunity discovery", "/strategy-opportunity/scan/opportunity-scanner-dashboard", "pending", "chart"],
    ["live-market-scanner", "Live Market Scanner", "Scan XAUUSD tick and structure conditions", "/strategy-opportunity/scan/live-market-scanner", "pending", "liquidity"],
    ["institutional-scanner", "Institutional Scanner", "Scan liquidity, order blocks and FVGs", "/strategy-opportunity/scan/institutional-scanner", "pending", "structure"],
    ["retail-scanner", "Retail Scanner", "Scan retail technical triggers", "/strategy-opportunity/scan/retail-scanner", "pending", "arrow"],
    ["h8-liquidity-scanner", "H8 Liquidity Scanner", "Scan H8 sweeps and continuation context", "/strategy-opportunity/scan/h8-liquidity-scanner", "pending", "levels"],
    ["h12-liquidity-scanner", "H12 Liquidity Scanner", "Scan H12 liquidity targets and reversals", "/strategy-opportunity/scan/h12-liquidity-scanner", "pending", "levels"],
    ["session-scanner", "Session Scanner", "Scan session highs, lows and transition behavior", "/strategy-opportunity/scan/session-scanner", "pending", "calendar"],
    ["news-scanner", "News Scanner", "Scan news windows and event restrictions", "/strategy-opportunity/scan/news-scanner", "pending", "news"],
    ["detected-opportunities", "Detected Opportunities", "Review opportunities found by scanners", "/strategy-opportunity/scan/detected-opportunities", "pending", "checklist"],
    ["scan-history", "Scan History", "Review scanner activity and outcomes", "/strategy-opportunity/scan/scan-history", "pending", "history"],
  ],
  qualify: [
    ["qualification-dashboard", "Opportunity Qualification Dashboard", "Coordinate opportunity validation and scoring", "/strategy-opportunity/qualify/opportunity-qualification-dashboard", "pending", "checklist"],
    ["qualification-queue", "Qualification Queue", "Review opportunities awaiting qualification", "/strategy-opportunity/qualify/qualification-queue", "pending", "matrix"],
    ["opportunity-details", "Opportunity Details", "Inspect opportunity evidence and lifecycle status", "/strategy-opportunity/qualify/opportunity-details", "pending", "chart"],
    ["top-down-validation", "Top-Down Validation", "Validate monthly through execution timeframe alignment", "/strategy-opportunity/qualify/top-down-validation", "pending", "calendar"],
    ["institutional-validation", "Institutional Validation", "Validate institutional concepts and targets", "/strategy-opportunity/qualify/institutional-validation", "pending", "structure"],
    ["retail-validation", "Retail Validation", "Validate retail technical evidence", "/strategy-opportunity/qualify/retail-validation", "pending", "arrow"],
    ["confluence-scoring", "Confluence Scoring", "Score all supporting and conflicting evidence", "/strategy-opportunity/qualify/confluence-scoring", "pending", "matrix"],
    ["entry-readiness", "Entry Readiness", "Check entry trigger, timing and confirmation state", "/strategy-opportunity/qualify/entry-readiness", "pending", "checklist"],
    ["qualified-opportunities", "Qualified Opportunities", "Review approved qualified opportunities", "/strategy-opportunity/qualify/qualified-opportunities", "pending", "history"],
  ],
  authorize: [
    ["authorization-dashboard", "Trade Authorization Dashboard", "Coordinate final trade authorization", "/risk-execution/authorize/trade-authorization-dashboard", "pending", "shield"],
    ["authorization-queue", "Authorization Queue", "Review trades awaiting authorization", "/risk-execution/authorize/authorization-queue", "pending", "matrix"],
    ["independent-risk-review", "Independent Risk Review", "Perform independent risk checks", "/risk-execution/authorize/independent-risk-review", "pending", "shield"],
    ["account-eligibility", "Account Eligibility", "Validate account conditions and rules", "/risk-execution/authorize/account-eligibility", "pending", "profile"],
    ["position-size-calculator", "Position Size Calculator", "Calculate risk-based position size", "/risk-execution/authorize/position-size-calculator", "pending", "chart"],
    ["final-trade-decision", "Final Trade Decision", "Approve, reduce, delay or reject trade", "/risk-execution/authorize/final-trade-decision", "pending", "checklist"],
    ["authorization-history", "Authorization History", "Review previous authorization decisions", "/risk-execution/authorize/authorization-history", "pending", "history"],
  ],
  execute: [
    ["execution-dashboard", "MT5 Execution Dashboard", "Supervise MT5 order execution", "/risk-execution/execute/mt5-execution-dashboard", "pending", "rocket"],
    ["execution-queue", "Execution Queue", "Review authorized orders awaiting routing", "/risk-execution/execute/execution-queue", "pending", "matrix"],
    ["market-orders", "Market Orders", "Submit and monitor market orders", "/risk-execution/execute/market-orders", "pending", "arrow"],
    ["pending-orders", "Pending Orders", "Place and manage pending orders", "/risk-execution/execute/pending-orders", "pending", "calendar"],
    ["buy-orders", "Buy Orders", "Review buy-side execution flow", "/risk-execution/execute/buy-orders", "pending", "chart"],
    ["sell-orders", "Sell Orders", "Review sell-side execution flow", "/risk-execution/execute/sell-orders", "pending", "chart"],
    ["broker-responses", "Broker Responses", "Inspect broker accepts, rejects and errors", "/risk-execution/execute/broker-responses", "pending", "warning"],
    ["execution-history", "Execution History", "Review execution results and audit records", "/risk-execution/execute/execution-history", "pending", "history"],
  ],
  manage: [
    ["position-management-dashboard", "Position Management Dashboard", "Supervise active positions and baskets", "/trade-operations/manage/position-management-dashboard", "pending", "chart"],
    ["active-positions", "Active Positions", "Monitor active XAUUSD positions", "/trade-operations/manage/active-positions", "pending", "liquidity"],
    ["active-baskets", "Active Baskets", "Monitor active baskets and aggregate state", "/trade-operations/manage/active-baskets", "pending", "matrix"],
    ["stop-loss-manager", "Stop-Loss Manager", "Adjust and protect stop loss levels", "/trade-operations/manage/stop-loss-manager", "pending", "shield"],
    ["break-even-manager", "Break-Even Manager", "Move positions to break-even when eligible", "/trade-operations/manage/break-even-manager", "pending", "checklist"],
    ["profit-lock-manager", "Profit-Lock Manager", "Lock profit based on policy and structure", "/trade-operations/manage/profit-lock-manager", "pending", "levels"],
    ["trailing-stop-manager", "Trailing-Stop Manager", "Trail stops behind price structure", "/trade-operations/manage/trailing-stop-manager", "pending", "arrow"],
    ["management-history", "Management Action History", "Review management actions and audit trail", "/trade-operations/manage/management-action-history", "pending", "history"],
  ],
  close: [
    ["trade-closure-dashboard", "Trade Closure Dashboard", "Coordinate closure queue and exit decisions", "/trade-operations/close/trade-closure-dashboard", "pending", "chart"],
    ["closure-queue", "Closure Queue", "Review trades awaiting closure", "/trade-operations/close/closure-queue", "pending", "matrix"],
    ["full-position-closure", "Full Position Closure", "Close complete positions", "/trade-operations/close/full-position-closure", "pending", "arrow"],
    ["basket-closure", "Basket Closure", "Close complete trading baskets", "/trade-operations/close/basket-closure", "pending", "liquidity"],
    ["partial-closure", "Partial Closure", "Close partial position volume", "/trade-operations/close/partial-closure", "pending", "levels"],
    ["emergency-closure", "Emergency Closure", "Handle emergency exit actions", "/trade-operations/close/emergency-closure", "pending", "warning"],
    ["completed-trades", "Completed Trades", "Review completed trades", "/trade-operations/close/completed-trades", "pending", "checklist"],
    ["closure-history", "Closure History", "Review closure events and reconciliation", "/trade-operations/close/closure-history", "pending", "history"],
  ],
  review: [
    ["post-trade-review-dashboard", "Post-Trade Review Dashboard", "Coordinate autonomous trade review", "/performance-control/review/post-trade-review-dashboard", "pending", "chart"],
    ["trade-journal", "Trade Journal", "Review journaled lifecycle decisions", "/performance-control/review/trade-journal", "pending", "history"],
    ["trade-details", "Trade Details", "Inspect trade execution and management details", "/performance-control/review/trade-details", "pending", "liquidity"],
    ["decision-replay", "Decision Replay", "Replay autonomous decision sequence", "/performance-control/review/decision-replay", "pending", "arrow"],
    ["risk-compliance", "Risk Compliance", "Review risk rule compliance", "/performance-control/review/risk-compliance", "pending", "shield"],
    ["strategy-performance", "Strategy Performance", "Measure strategy outcome and quality", "/performance-control/review/strategy-performance", "pending", "matrix"],
    ["review-history", "Review History", "Review historical review outputs", "/performance-control/review/review-history", "pending", "history"],
  ],
  learn: [
    ["learning-dashboard", "Learning Dashboard", "Coordinate model and strategy learning", "/performance-control/learn/learning-dashboard", "pending", "sentiment"],
    ["pattern-discovery", "Pattern Discovery", "Discover winning and losing pattern traits", "/performance-control/learn/pattern-discovery", "pending", "matrix"],
    ["strategy-optimization", "Strategy Optimization", "Optimize strategy thresholds and filters", "/performance-control/learn/strategy-optimization", "pending", "settings"],
    ["model-performance", "Model Performance", "Monitor model performance and drift", "/performance-control/learn/model-performance", "pending", "chart"],
    ["backtesting-studio", "Backtesting Studio", "Backtest strategies and variants", "/performance-control/learn/backtesting-studio", "pending", "calendar"],
    ["model-governance", "Model Governance", "Govern model versions and promotions", "/performance-control/learn/model-governance", "pending", "shield"],
    ["learning-history", "Learning History", "Review learning outputs and changes", "/performance-control/learn/learning-history", "pending", "history"],
  ],
  repeat: [
    ["autonomous-loop-dashboard", "Autonomous Loop Dashboard", "Monitor the next autonomous lifecycle cycle", "/performance-control/repeat/autonomous-loop-dashboard", "pending", "rocket"],
    ["current-cycle", "Current Cycle", "Inspect current cycle state", "/performance-control/repeat/current-cycle", "pending", "chart"],
    ["cycle-monitor", "Cycle Monitor", "Track loop readiness and cycle events", "/performance-control/repeat/cycle-monitor", "pending", "structure"],
    ["reanalysis-trigger", "Reanalysis Trigger", "Trigger controlled market reanalysis", "/performance-control/repeat/reanalysis-trigger", "pending", "arrow"],
    ["cooldown-controller", "Cooldown Controller", "Manage cooldown and trade frequency", "/performance-control/repeat/cooldown-controller", "pending", "calendar"],
    ["loop-limits", "Loop Limits", "Review repeat limits and safeguards", "/performance-control/repeat/loop-limits", "pending", "shield"],
    ["loop-history", "Loop History", "Review lifecycle loop history", "/performance-control/repeat/loop-history", "pending", "history"],
  ],
  stop: [
    ["controlled-shutdown-dashboard", "Controlled Shutdown Dashboard", "Coordinate controlled lifecycle shutdown", "/performance-control/stop/controlled-shutdown-dashboard", "not-started", "shield"],
    ["stop-new-trades", "Stop New Trades", "Prevent new opportunities from advancing", "/performance-control/stop/stop-new-trades", "not-started", "warning"],
    ["stop-after-active-trades", "Stop After Active Trades", "Stop after active positions complete", "/performance-control/stop/stop-after-active-trades", "not-started", "calendar"],
    ["cancel-orders-and-stop", "Cancel Orders and Stop", "Cancel pending orders and halt lifecycle", "/performance-control/stop/cancel-orders-and-stop", "not-started", "arrow"],
    ["close-and-stop", "Close and Stop", "Close open exposure and stop", "/performance-control/stop/close-and-stop", "not-started", "liquidity"],
    ["emergency-stop", "Emergency Stop", "Immediately stop critical autonomous activity", "/performance-control/stop/emergency-stop", "not-started", "warning"],
    ["shutdown-history", "Shutdown History", "Review shutdown history and restart eligibility", "/performance-control/stop/shutdown-history", "not-started", "history"],
  ],
};

const stageInputs: Record<string, string[]> = {
  start: ["Operating Mode", "Trading Profile", "Risk Profile", "Startup Policy"],
  initialize: ["Environment Config", "Agent Registry", "Model Versions", "Service Map"],
  connect: ["MT5 Credentials", "Broker Session", "Market Data Feed", "News Feed"],
  validate: ["Account State", "Symbol Specs", "Risk Limits", "Strategy Rules"],
  synchronize: ["Tick Feed", "Candle History", "Account Snapshot", "Session Clock"],
  analyse: ["Live Market Data", "News & Economic Calendar", "COT & Sentiment Data", "Historical Price Data", "Strategy Parameters"],
  plan: ["Market Bias", "Risk Budget", "Session Windows", "News Restrictions"],
  scan: ["Trading Plan", "Live Ticks", "Liquidity Map", "Session Levels"],
  qualify: ["Detected Opportunity", "Analysis Evidence", "Risk Context", "News Context"],
  authorize: ["Qualified Opportunity", "Account Eligibility", "Risk Limits", "Position Size"],
  execute: ["Authorized Trade", "Broker Route", "Order Parameters", "Slippage Policy"],
  manage: ["Open Positions", "Basket State", "Structure Updates", "Risk Protections"],
  close: ["Exit Signal", "Open Exposure", "Broker State", "Closure Policy"],
  review: ["Completed Trade", "Decision Timeline", "Execution Logs", "Risk Events"],
  learn: ["Review Output", "Pattern Data", "Strategy Metrics", "Model Telemetry"],
  repeat: ["Cycle State", "Cooldown Policy", "Session State", "Loop Limits"],
  stop: ["Stop Policy", "Open Exposure", "Pending Orders", "Emergency Rules"],
};

const stageOutputs: Record<string, string[]> = {
  start: ["Startup Approval", "Operating State", "Startup Audit"],
  initialize: ["Initialized Engines", "Active Agents", "Loaded Configuration"],
  connect: ["Connected Services", "Live Data Channels", "Connection Audit"],
  validate: ["Readiness Decision", "Validation Exceptions", "Eligibility State"],
  synchronize: ["Synced Market State", "Synced Account State", "Data Quality Status"],
  analyse: ["Market Bias", "Trading Scenarios", "High Probability Zones", "Trade Setups for Planning Stage"],
  plan: ["Daily Plan", "Trading Windows", "Risk Allocation", "No-Trade Rules"],
  scan: ["Detected Opportunities", "Scanner Evidence", "Opportunity Alerts"],
  qualify: ["Qualified Opportunities", "Rejected Opportunities", "Confluence Score"],
  authorize: ["Approved Trades", "Reduced-Risk Approvals", "Rejected Authorizations"],
  execute: ["Execution Result", "Broker Confirmation", "Execution Incidents"],
  manage: ["Management Actions", "Protected Basket", "Updated Stops"],
  close: ["Closed Trades", "Closure Reconciliation", "Completed Trade Records"],
  review: ["Trade Review", "Compliance Result", "Performance Attribution"],
  learn: ["Optimization Recommendation", "Updated Model Metrics", "Learning Record"],
  repeat: ["Next Cycle Readiness", "Loop Decision", "Cycle History"],
  stop: ["Shutdown State", "Stopped Services", "Restart Eligibility"],
};

export const stageDefinitions = [
  ["start", "START", "Foundation", "Boot and activate the autonomous engine."],
  ["initialize", "INITIALIZE", "Foundation", "Load configuration, policies, models and runtime services."],
  ["connect", "CONNECT", "Foundation", "Connect broker, market, database and intelligence services."],
  ["validate", "VALIDATE", "Foundation", "Validate runtime, data, strategy and risk controls."],
  ["synchronize", "SYNCHRONIZE", "Foundation", "Synchronize market, account and system state."],
  ["analyse", "ANALYSE", "Market Intelligence", "Perform comprehensive market analysis across all dimensions to determine market bias and trading opportunities."],
  ["plan", "PLAN", "Opportunity", "Prepare strategy, scenarios and risk-aware trading plan."],
  ["scan", "SCAN", "Opportunity", "Continuously scan XAUUSD for valid opportunities."],
  ["qualify", "QUALIFY", "Opportunity", "Score and qualify trading opportunities."],
  ["authorize", "AUTHORIZE", "Risk & Execution", "Apply autonomous policy and risk authorization."],
  ["execute", "EXECUTE", "Risk & Execution", "Execute the approved trading basket."],
  ["manage", "MANAGE", "Position Management", "Protect, lock, trail and manage positions."],
  ["close", "CLOSE", "Position Management", "Close positions and reconcile orders."],
  ["review", "REVIEW", "Continuous Improvement", "Review performance, risk and compliance outcomes."],
  ["learn", "LEARN", "Continuous Improvement", "Update memory, models and operating knowledge."],
  ["repeat", "REPEAT", "Continuous Improvement", "Begin the next controlled lifecycle cycle."],
  ["stop", "STOP", "Continuous Improvement", "Perform safe autonomous shutdown when required."],
] as const;

export const lifecycleSnapshot: LifecycleSnapshot = {
  updatedAt: new Date().toISOString(),
  symbol: "XAUUSD",
  price: "2,425.36",
  priceChange: "+8.74 (0.36%)",
  accountMode: "Live Account",
  progress: 78,
  currentStageKey: "analyse",
  kpis: [
    { label: "Lifecycle Progress", value: "72%", helper: "11 / 16 stages completed", tone: "violet", trend: [20, 29, 34, 43, 51, 60, 69, 78] },
    { label: "Active Workflows", value: "12", helper: "Running autonomous cycles", tone: "blue", trend: [5, 8, 6, 9, 8, 11, 10, 12] },
    { label: "Open Positions", value: "37", helper: "+24.3% XAUUSD", tone: "green", trend: [13, 16, 22, 21, 28, 31, 37] },
    { label: "Today's P&L", value: "+$18,742.50", helper: "Autonomous performance", tone: "green", trend: [2, 4, 3, 7, 9, 12, 11, 18] },
    { label: "Account Equity", value: "$772,894.20", helper: "Current account value", tone: "violet", trend: [70, 72, 71, 74, 73, 76, 77] },
    { label: "Risk Exposure", value: "48%", helper: "Within limits", tone: "orange", trend: [35, 39, 42, 40, 45, 46, 48] },
    { label: "System Health", value: "Excellent", helper: "All engines operational", tone: "green", trend: [92, 94, 96, 97, 98, 99] },
  ],
  stages: stageDefinitions.map(([key, name, group, summary], index) => {
    const completed = index < 5;
    const active = key === "analyse";
    return {
      id: index + 1,
      key,
      name,
      group,
      summary,
      status: completed ? "completed" : active ? "in-progress" : key === "stop" ? "not-started" : "pending",
      progress: completed ? 100 : active ? 87 : 0,
      startedAt: active ? "10:18 AM" : undefined,
      elapsed: active ? "00:06:32" : undefined,
      estimatedCompletion: active ? "00:03:28" : undefined,
      readiness: active ? 87 : completed ? 100 : 0,
      pages: (stagePages[key] ?? []).map(([id, title, description, href, status, icon]) => ({ id, title, description, href, status, icon })),
      inputs: stageInputs[key] ?? [],
      outputs: stageOutputs[key] ?? [],
    } satisfies LifecycleStage;
  }),
  activity: [
    { id: "1", time: "10:24:12", message: "H1 bullish structure confirmed", tone: "success" },
    { id: "2", time: "10:23:45", message: "Liquidity sweep detected at 2421.80", tone: "success" },
    { id: "3", time: "10:22:31", message: "COT data bias: Bullish (78%)", tone: "info" },
    { id: "4", time: "10:21:56", message: "Analysis confluence score: 82/100", tone: "success" },
    { id: "5", time: "10:20:14", message: "Key resistance zone: 2425.00", tone: "warning" },
  ],
};
